playersList:
    path: /list
    controller: App\Controller\Players\Main::players
    methods: GET
    
playerForm:
    path: /form/{id}
    controller: App\Controller\Players\Main::form
    methods: GET
    requirements:
        id: \d+|-1    
    defaults:
        id: -1

playerPost:
    path: /post
    controller: App\Controller\Players\Main::post
    methods: POST
    
playerDelete:
    path: /delete/{id}
    controller: App\Controller\Players\Main::delete
    methods: GET
    requirements:
        id: \d+|-1    
    defaults:
        id: -1

playerSearch:
    path: /search/{text}
    controller: App\Controller\Players\Main::search
    methods: GET
    defaults:
        text: ''
    