stagesList:
    path: /list/{competition_id}
    controller: App\Controller\Competitions\Stages::stages
    methods: GET
    requirements:
        competition_id: \d+|-1
    defaults:
        competition_id: -1

stageCreateForm:
    path: /create/form/{competition_id}
    controller: App\Controller\Competitions\Stages::addForm
    methods: GET
    requirements:
        competition_id: \d+|-1
    defaults:
        competition_id: -1

stageEditForm:
    path: /edit/form/{id}
    controller: App\Controller\Competitions\Stages::editForm
    methods: GET
    requirements:
        id: \d+|-1
    defaults:
        id: -1

stageCreate:
    path: /create
    controller: App\Controller\Competitions\Stages::create
    methods: POST

stagePost:
    path: /post
    controller: App\Controller\Competitions\Stages::post
    methods: POST

stageDelete:
    path: /delete/{id}
    controller: App\Controller\Competitions\Stages::delete
    methods: GET
    requirements:
        id: \d+|-1
    defaults:
        id: -1

stageView:
    path: /view/{id}
    controller: App\Controller\Competitions\Stages::view
    methods: GET
    requirements:
        id: \d+|-1
    defaults:
        id: -1

stageGames:
    path: /games/{id}
    controller: App\Controller\Competitions\Stages::games
    methods: GET
    requirements:
        id: \d+|-1
    defaults:
        id: -1

stageFreeCompetitors:
    path: /freecompetitord/{id}
    controller: App\Controller\Competitions\Stages::freeCompetitors
    requirements:
        id: \d+|-1
    defaults:
        id: -1