mainPage:
    path: /
    controller: App\Controller\MainPage::index

admin:
    resource: routes/admin.yaml
    prefix: /admin

players:
    resource: routes/players.yaml
    prefix: /players

courts:
    resource: routes/courts.yaml
    prefix: /courts
    
competitions:
    resource: routes/competitions/main.yaml
    prefix: /competition