mainPage:
    path: /
    controller: App\Controller\MainPage::index
    
players: 
    resource: routes/players.yaml
    prefix: /players

courts: 
    resource: routes/courts.yaml
    prefix: /courts    